Import('env', 'object_files')


src = [
    "ClientService.cc",
    "ControlService.cc",
    "Globals.cc",
    "RaftConsensus.cc",
    "RaftConsensusInvariants.cc",
    "RaftService.cc",
    "StateMachine.cc",
]

if not env["IX"]:
   src.append("ServerStats.cc")

object_files['Server'] = (env.StaticObject(src) +
                          env.Protobuf("SnapshotMetadata.proto") +
                          env.Protobuf("SnapshotStateMachine.proto") +
                          env.Protobuf("SnapshotStats.proto"))
